-- This file documents that the Supabase schema for the POS app has been aligned.
-- The companion file 2025-11-05-align-schema.sql contains the idempotent DDL covering:
-- - Table creation (if not exists)
-- - Column alignment and type precision
-- - Indexes on foreign keys and common filters
-- - RLS enabled across all tables
-- - Authenticated read/write policies
-- - PostgREST schema reload via pg_notify
